name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repozytorium
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Zainstaluj zależności
      run: |
        python -m pip install --upgrade pip
        pip install Django djangorestframework
        # Jeśli masz plik requirements.txt, użyj: pip install -r requirements.txt

    - name: Wykonaj migracje
      run: python manage.py migrate

    - name: Uruchom testy
      run: python manage.py test
